server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: STOCK
          uri: lb://STOCK
          predicates:
            - Path=/api/stock/**
          filters:
            - name: CircuitBreaker
              args:
                  name: STOCK
                  fallbackuri: forward:/stockServiceFallBackMethod
        - id: CUSTOMER
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/customers/**
          filters:
            - name: CircuitBreaker
              args:
                name: CUSTOMER
                fallbackuri: forward:/customerServiceFallBackMethod


hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream