server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: STOCK
          uri: lb://STOCK
          predicates:
            - Path=/api/stock/**
        - id: CUSTOMER
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/customers/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost