server:
  port: 8081

spring:
  application:
    name: STOCK
  zipkin:
    base-url: http://127.0.0.1:9411/
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/customer
    username: root
    password: amedakevin1997
    driver-class-name: com.mysql.cj.jdbc.Driver
