server:
  port: 8081

spring:
  application:
    name: STOCK
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/customer
    username: root
    password: amedakevin1997
    driver-class-name: com.mysql.cj.jdbc.Driver


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost